/*
 * xval_test.c — cross-validation of the engine's core spatial math against INDEPENDENT
 * reference implementations (golden vectors in xval_data.h, generated by
 * tools/xval/gen_reference.py with numpy/scipy — see its header for the provenance):
 *
 *   ambisonics.c  vs scipy.special.lpmv real SN3D/ACN spherical harmonics (and, inside the
 *                 generator, phonon's hardcoded orthonormal-SH table as a third source);
 *   hull.c        vs the l1-optimal linear program of Franck/Wang/Fazi 2017 (scipy linprog/
 *                 HiGHS): with non-negative gains its unique solution IS VBAP, so a simplex
 *                 solver cross-checks the geometric hull walk — and vs qhull, which the
 *                 generator agrees with before pinning either;
 *   allrad.c      vs a full decode rebuild on qhull + numpy solves + scipy SH, including
 *                 the imaginary-pole-speaker rule (both the covered and floor-less grids);
 *   biquad.h      vs the RBJ analog prototypes bilinear-transformed with pre-warping
 *                 (scipy.signal.bilinear) — an independent derivation of the cookbook;
 *   align.c       vs a scipy.signal.lfilter float64 rendering of the room_eq cascade.
 *
 * DBAP/SPCAP are house designs (listener-relative weighting, placement correction) and the
 * MDAP ring parametrization is an implementation choice — no external reference exists for
 * those; their contracts live in the dsp/rt property tests, and their shared cores (the
 * hull/VBAP solve, the SH encode, the biquads) are exactly what this test pins.
 */
#include "layout.h"
#include "hull.h"
#include "allrad.h"
#include "ambisonics.h"
#include "biquad.h"
#include "align.h"

#include "xval_data.h"

#include <math.h>
#include <stdio.h>
#include <string.h>

#define CH BWA_CHANNELS

static int fails = 0;
#define CHECK(c, msg) do { if (!(c)) { printf("FAIL: %s\n", msg); ++fails; } } while (0)

enum { MAXTRI = 512 };

int main(void) {
    /* 1. SH encode vs scipy: all 16 ACN/SN3D channels at 64 quasi-random directions */
    {
        float maxerr = 0.f;
        for (int i = 0; i < XVAL_SH_N; ++i) {
            float y[BWA_AMBI_CH];
            ambi_encode_sn3d(&xval_sh_dir[i * 3], y);
            for (int k = 0; k < BWA_AMBI_CH; ++k) {
                float e = fabsf(y[k] - xval_sh_val[i * BWA_AMBI_CH + k]);
                if (e > maxerr) maxerr = e;
            }
        }
        printf("xval sh: max |err| = %.3g\n", maxerr);
        CHECK(maxerr < 1e-5f, "SH encode matches scipy lpmv real SN3D harmonics (16 ch, 64 dirs)");
    }

    /* 2. hull.c VBAP vs the l1-optimal LP (Franck/Wang/Fazi 2017): same active speakers,
     * same normalized gains, for 64 directions over the default grid's hull */
    {
        Layout L = layout_default();
        float dirs[CH][3];
        for (int s = 0; s < CH; ++s) {
            float p[3] = { L.speakers[s].pos[0] - L.ref[0], L.speakers[s].pos[1] - L.ref[1],
                           L.speakers[s].pos[2] - L.ref[2] };
            float n = sqrtf(p[0]*p[0] + p[1]*p[1] + p[2]*p[2]);
            dirs[s][0] = p[0]/n; dirs[s][1] = p[1]/n; dirs[s][2] = p[2]/n;
        }
        static int tri[MAXTRI][3]; static float det[MAXTRI];
        int ntri = hull_triangulate(dirs, CH, tri, det, MAXTRI);
        CHECK(ntri > 0, "default grid triangulates");
        float maxerr = 0.f;
        int active_ok = 1;
        for (int i = 0; i < XVAL_VBAP_N && ntri > 0; ++i) {
            int spk[3]; float g3[3];
            CHECK(hull_vbap(&xval_vbap_dir[i * 3], dirs, tri, det, ntri, spk, g3), "hull_vbap solves");
            float g[CH]; memset(g, 0, sizeof g);
            for (int q = 0; q < 3; ++q) g[spk[q]] += g3[q];
            for (int s = 0; s < CH; ++s) {
                float ref = xval_vbap_gain[i * CH + s];
                float e = fabsf(g[s] - ref);
                if (e > maxerr) maxerr = e;
                if ((ref > 1e-4f) != (g[s] > 1e-4f)) active_ok = 0;   /* same speakers carry it */
            }
        }
        printf("xval vbap: max |err| = %.3g\n", maxerr);
        CHECK(maxerr < 1e-4f, "hull_vbap gains match the l1-optimal LP solution (VBAP = sparse l1)");
        CHECK(active_ok, "hull_vbap activates the same speaker set the LP does");
    }

    /* 3. allrad.c vs the qhull + linprog + scipy rebuild — full matrices, both grids */
    {
        Layout L = layout_default();
        float dec[BWA_CHANNELS][BWA_AMBI_CH];
        CHECK(allrad_build_decode(&L, dec), "allrad builds (grid26)");
        double fro2 = 0, ref2 = 0; float maxerr = 0.f;
        for (int s = 0; s < CH; ++s)
            for (int k = 0; k < BWA_AMBI_CH; ++k) {
                float ref = xval_allrad_grid26[s * BWA_AMBI_CH + k];
                float e = fabsf(dec[s][k] - ref);
                if (e > maxerr) maxerr = e;
                fro2 += (double)e * e; ref2 += (double)ref * ref;
            }
        printf("xval allrad26: max |err| = %.3g  rel frob = %.3g\n", maxerr, sqrt(fro2 / ref2));
        CHECK(maxerr < 1e-4f && fro2 / ref2 < 1e-4 * 1e-4,
              "AllRAD decode matrix matches the qhull rebuild (covered grid)");

        Layout LH; memset(&LH, 0, sizeof LH);          /* the floor-less grid: exercises the
                                                        * imaginary nadir speaker in BOTH builds */
        uint32_t nh = 0;
        for (uint32_t s = 0; s < L.count; ++s) {
            if (L.speakers[s].pos[1] < 0.1f) continue;
            memcpy(LH.speakers[nh].pos, L.speakers[s].pos, sizeof LH.speakers[nh].pos);
            LH.speakers[nh].gain_lin = 1.f;
            ++nh;
        }
        LH.count = nh;
        layout_compute_ref(&LH);
        CHECK(nh == 17 && allrad_build_decode(&LH, dec), "allrad builds (floorless17)");
        fro2 = ref2 = 0; maxerr = 0.f;
        for (uint32_t s = 0; s < nh; ++s)
            for (int k = 0; k < BWA_AMBI_CH; ++k) {
                float ref = xval_allrad_floorless17[s * BWA_AMBI_CH + k];
                float e = fabsf(dec[s][k] - ref);
                if (e > maxerr) maxerr = e;
                fro2 += (double)e * e; ref2 += (double)ref * ref;
            }
        printf("xval allrad17: max |err| = %.3g  rel frob = %.3g\n", maxerr, sqrt(fro2 / ref2));
        CHECK(maxerr < 1e-4f && fro2 / ref2 < 1e-4 * 1e-4,
              "AllRAD imaginary-speaker decode matches the qhull rebuild (floor-less grid)");
    }

    /* 4. biquad.h vs scipy.signal.bilinear of the RBJ analog prototypes: 108 cases across
     * peak + both shelves (the room_eq / occlusion / pathing EQ sections), 48/96 kHz */
    {
        float maxerr = 0.f;
        for (int i = 0; i < XVAL_BQ_N; ++i) {
            const float* c = &xval_bq_case[i * 5];
            float co[5];
            bwa_biquad_rbj_hz((int)c[0], (double)c[1], (double)c[2], (double)c[3], (double)c[4], co);
            for (int k = 0; k < 5; ++k) {
                float e = fabsf(co[k] - xval_bq_coef[i * 5 + k]);
                if (e > maxerr) maxerr = e;
            }
        }
        printf("xval biquad: max |err| = %.3g\n", maxerr);
        CHECK(maxerr < 1e-6f, "RBJ cookbook coefficients match the bilinear-transformed prototypes");
    }

    /* 5. align.c room_eq rendering vs scipy.signal.lfilter: rt.c's LCG noise through the
     * two-section cascade on channel 0, one 4096-sample block, float32 DF-I vs float64 */
    {
        Layout L = layout_default();
        L.speakers[0].room_eq_count = 2;
        L.speakers[0].room_eq[0].fc = 45.f;  L.speakers[0].room_eq[0].gain_db = -8.f; L.speakers[0].room_eq[0].q = 6.f;
        L.speakers[0].room_eq[1].fc = 120.f; L.speakers[0].room_eq[1].gain_db = -5.f; L.speakers[0].room_eq[1].q = 2.f;
        Aligner* a = align_create(CH, &L, 48000);
        CHECK(a != NULL, "align_create (xval)");
        if (a) {
            static float bus[CH * XVAL_LF_N];
            memset(bus, 0, sizeof bus);
            uint32_t s = 1;                            /* rt.c's LCG — the generator's input spec */
            for (int i = 0; i < XVAL_LF_N; ++i) {
                s = s * 1664525u + 1013904223u;
                bus[i] = (float)(s >> 9) * (1.0f / 4194304.0f) - 1.0f;
            }
            align_process(a, bus, XVAL_LF_N);
            double err2 = 0, ref2 = 0; float maxerr = 0.f;
            for (int i = 0; i < XVAL_LF_N; ++i) {
                float e = fabsf(bus[i] - xval_lf_out[i]);
                if (e > maxerr) maxerr = e;
                err2 += (double)e * e; ref2 += (double)xval_lf_out[i] * xval_lf_out[i];
            }
            printf("xval lfilter: max |err| = %.3g  rel rms = %.3g\n", maxerr, sqrt(err2 / ref2));
            CHECK(sqrt(err2 / ref2) < 1e-3 && maxerr < 5e-3f,
                  "align room_eq rendering matches the scipy lfilter cascade");
            align_destroy(a);
        }
    }

    if (fails) { printf("xval_test: %d FAILURES\n", fails); return 1; }
    printf("xval_test OK (SH vs scipy, VBAP vs l1-LP, AllRAD vs qhull rebuild, RBJ vs bilinear, align vs lfilter)\n");
    return 0;
}
