#!/usr/bin/env python3
"""Generate examples/dome_24.json: the playground demos' default speaker array.

Also writes the identical copy the Godot addon ships
(bindings/godot/addons/bw_audio/playground/dome_24.json), so the two cannot drift. The web
page takes examples/dome_24.json through tools/wasm/build-web.sh.

A generic dome, not a surveyed rig: 24 speakers on a 2 m sphere around a listening point
1.5 m above the floor, spread evenly over the part of the sphere that is ABOVE the floor.
Evenly means a Fibonacci lattice uniform in height (equal-area bands on a sphere) between
the floor cut and the top, with the golden-angle azimuth. A hemisphere would waste the
band between ear level and the floor that a real room can still reach; a full sphere would
put speakers under the floor. The i + 0.5 offset keeps both ends of the range off a pole.

Stdlib only, deterministic. Run: uv run tools/layout/gen_dome.py
"""
import json
import math
import pathlib

N = 24             # speaker count
RADIUS_M = 2.0     # sphere radius around the listening point
CENTER_Y_M = 1.5   # listening-point height, same as the default grid's cube center
FLOOR_Y_M = 0.0

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "examples" / "dome_24.json"
COPIES = [ROOT / "bindings" / "godot" / "addons" / "bw_audio" / "playground" / "dome_24.json"]


def dome():
    # height (relative to the center) runs from the floor cut to the top of the sphere
    h_lo = max(-RADIUS_M, FLOOR_Y_M - CENTER_Y_M)
    h_hi = RADIUS_M
    golden = math.pi * (3.0 - math.sqrt(5.0))
    pts = []
    for i in range(N):
        h = h_lo + (h_hi - h_lo) * (i + 0.5) / N
        rho = math.sqrt(max(RADIUS_M * RADIUS_M - h * h, 0.0))
        az = golden * i
        pts.append([round(rho * math.cos(az), 3), round(CENTER_Y_M + h, 3), round(rho * math.sin(az), 3)])
    return pts


def main():
    pts = dome()
    doc = {
        "schema_version": 1,
        "note": "GENERATED by tools/layout/gen_dome.py - do not hand-edit; rerun the script. "
                "A generic 24-speaker dome for the playground demos, not a surveyed rig.",
        "units": {"position": "meters", "gain": "decibels", "delay": "milliseconds"},
        "listening_point_m": [0.0, CENTER_Y_M, 0.0],
        "coordinate_space": "room, right-handed, +y up, +z forward (matches OptiTrack/Motive default); "
                            "origin ON THE FLOOR at the working-area center (x/z); y = height above the floor",
        "reference": {
            "alignment": "max-distance",
            "ears_m": CENTER_Y_M,
            "speed_of_sound_mps": 343,
            "note": f"every speaker is {RADIUS_M:g} m from the listening point (0, {CENTER_Y_M:g}, 0), "
                    "so gain_db and delay_ms are all 0",
        },
        "dbap": {
            "distance_attenuation": {
                "model": "inverse",
                "reference_distance_m": 1,
                "rolloff": 1,
                "min_gain_db": -40,
            }
        },
        "speakers": [
            {"index": i, "position": p, "gain_db": 0, "delay_ms": 0} for i, p in enumerate(pts)
        ],
    }
    text = json.dumps(doc, indent=2) + "\n"
    for path in [OUT] + COPIES:
        path.write_text(text, encoding="utf-8", newline="\n")

    def elev(p):
        return math.degrees(math.asin((p[1] - CENTER_Y_M) / RADIUS_M))

    def unit(p):
        v = (p[0], p[1] - CENTER_Y_M, p[2])
        n = math.sqrt(sum(c * c for c in v))
        return tuple(c / n for c in v)

    units = [unit(p) for p in pts]
    nn = []
    for i, a in enumerate(units):
        best = min(math.degrees(math.acos(max(-1.0, min(1.0, sum(x * y for x, y in zip(a, b))))))
                   for j, b in enumerate(units) if j != i)
        nn.append(best)
    rerr = max(abs(math.dist(p, (0.0, CENTER_Y_M, 0.0)) - RADIUS_M) for p in pts)
    print(f"{OUT.name}: {N} speakers, radius {RADIUS_M:g} m at y={CENTER_Y_M:g}, "
          f"elevation {min(map(elev, pts)):.1f}..{max(map(elev, pts)):.1f} deg, "
          f"nearest neighbor {min(nn):.1f}..{max(nn):.1f} deg, max radius error {rerr * 1000:.2f} mm")


if __name__ == "__main__":
    main()
